# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a291bd1e2193c1010993b8b5a407c28ca9df049ccaf653a8a537f8d514d0e4dca6de5b50f728eb28756c495d8c69d4e0ce0279eea8a36ced6946149b5d65b68

test:
  secret_key_base: fb60689619808ad571069119908f6a04456cd033e36904d6c8af0237ca9c03169a03f31dc6b97eecbc6dc9b9326186643a5f2f19148bd177623a7630388e72e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
